/*

       --------------------written by KISHORE VARMA-------------------------------

       **************************************************************************
       Even Fibonacci numbers                                            Problem 2

       Each new term in the Fibonacci sequence is generated by adding the previous
       two terms. By starting with 1 and 2, the first 10 terms will be:

              1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

       By considering the terms in the Fibonacci sequence whose values do not exceed
       four million, find the sum of the even-valued terms.

                   answer is                 4613732
                                ------------------------------------

       *************************************************************************
    ideas :-

        1)  generate fibonacci sequence and check if new number is divisible by 2


        thats it we are ready to solve this Problem :)

      ***************************************************************************
      --------------------written by KISHORE VARMA-------------------------------
      ***************************************************************************
*/
#include<stdio.h>
// val is value upto which sum should be found
#define val 4000000
//below will work on 64 bit systems becuase int is 4 byte in such systems
int main()
{
  int prev=0,next=1,newno=0,sum=0;
  while(newno<val)
  {
    newno=prev+next;
    prev=next;
    next=newno;
    if (newno%2==0) sum+=newno;
  }
  printf("%d\n",sum);
  return 0;
}
